### ISSUE TITLE
Membership lentele

### ISSUE THREAD

**Issue by aleksas** [ruslanasa/lithuania.ai#1]
![image](https://user-images.githubusercontent.com/594470/73174011-63a08300-410f-11ea-91e8-697d5379e4cf.png)

Gal lentelę į atskirą psl per nuoroda "Membership details"?

Cia tam kad neperkrauti single page'o.
Tirkiausiai daugiau bus klausimu/info susijusiu su naryste, tai realiai ateiciai galima palikti.

**Comment by ruslanasa** [comment]
Kolkas buvo nuomone kad laikyt fronte.... reiktu tada pasitart su platesniu ratu. Paziurek restylinga ir jei ok uzdaryk, jei ne lets vote
