### ISSUE TITLE
Logo prie About

### ISSUE THREAD

**Issue by aleksas** [ruslanasa/lithuania.ai#2]
Truksta logo pradžioj, dabar tik pačioj apačioj yra.

Kiek suprantu turetu buti easy prideti prie aBout kaip pavyzdiniame variante:

![image](https://user-images.githubusercontent.com/594470/73174385-47e9ac80-4110-11ea-958f-feb7142b5320.png)

vietoj puodelio

**Comment by ruslanasa** [comment]
Darysim restyle link savgalio

**Comment by ruslanasa** [comment]
restylingas padarytas, sita problema issisprende
